# Computerphysik Programmiertutorial 4b
Prof. Dr. Matteo Rizzi und Dr. Markus Schmitt - Institut für Theoretische Physik, Universität zu Köln
&nbsp;

**Github**: [https://github.com/markusschmitt/compphys2022](https://github.com/markusschmitt/compphys2022)

**Inhalt dieses Notebooks**: Array-Abstraktionen, LinearAlgebra: Matrix/Vektor-Produkte, spezielle Matrizen, Matrixinversion, besondere Funktionen von Matrizen und Vektoren, Eigenwertprobleme, Singulärwertzerlegung, QR-Zerlegung

## Array-Abstraktionen (Array Comprehension)

Mit Array-Abstraktionen können Arrays oder andere iterierbare Datenstrukturen einfach "weiterverarbeitet" werden um daraus neue Arrays zu erzeugen.

Syntax:
```julia
neues_array = [<Anweisung> for <Variable> in <iterierbare Datenstruktur> if <Bedingung>]
```

Beispiel:

In [8]:
arr = [2n for n in 1:10]



10-element Vector{Int64}:
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20

In [9]:
arr = [2n for n in 1:10 if n%2==0]

5-element Vector{Int64}:
  4
  8
 12
 16
 20

## Lineare Algebra

Hier führen wir einen Teil der Funktionen des `LinearAlgebra` Pakets ein. Für einen vollständigen Überblick, siehe [Dokumentation](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/).

In [ ]:
using LinearAlgebra

### Matrixprodukte und -transformationen

Wir beschaffen uns zunächst zwei $3\times3$ Matrizen

In [11]:
A = reshape([1.0*n for n in 1:9], 3,3)

3×3 Matrix{Float64}:
 1.0  4.0  7.0
 2.0  5.0  8.0
 3.0  6.0  9.0

In [12]:
B=rand(3,3)

3×3 Matrix{Float64}:
 0.607617  0.677263  0.397088
 0.980097  0.389364  0.303848
 0.331435  0.856833  0.653452

Das übliche Matrixprodukt wird durch den `*` Operator berechnet:

In [13]:
A * B

3×3 Matrix{Float64}:
  6.84805   8.23255  6.18664
  8.7672   10.156    7.54103
 10.6863   12.0795   8.89541

Elementweise Multiplikation der Einträge erfolgt durch `.*`

In [14]:
A .* B

3×3 Matrix{Float64}:
 0.607617  2.70905  2.77961
 1.96019   1.94682  2.43078
 0.994304  5.141    5.88107

Eine Matrix kann durch die Funktion `transpose` transponiert werden.

In [ ]:
transpose(A)

Durch Nachstellen von `'` wird die Matrix transponiert und komplex konjugiert:

In [15]:
(1.0im*A)'

3×3 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 0.0-1.0im  0.0-2.0im  0.0-3.0im
 0.0-4.0im  0.0-5.0im  0.0-6.0im
 0.0-7.0im  0.0-8.0im  0.0-9.0im

### Vektorprodukte

Es gibt verschiedene Optionen das Skalarprodukt zweier Vektoren zu berechnen:

In [16]:
v1=[1.0im,2.0,3.0]
v2=[3.0,6.0,9.0]

3-element Vector{Float64}:
 3.0
 6.0
 9.0

In [17]:
dot(v1, v2)

39.0 - 3.0im

In [18]:
v1' * v2

39.0 - 3.0im

Transponieren des ersten Vektors funktioniert ebenfalls bei reellen Zahlen, aber liefert bei komplexen Zahlen natürlich nicht das gewünschte Ergebnis:

In [19]:
transpose(v1) * v2

39.0 + 3.0im

Außerdem ist das Kreuzprodukt in der Funktion `cross` implementiert:

In [20]:
cross(v1, v2)

3-element Vector{ComplexF64}:
  0.0 + 0.0im
  9.0 - 9.0im
 -6.0 + 6.0im

### Spezielle Matrizen

Spezielle Matrizen, die weitere Struktur haben, können besonders behandelt werden, z.B. aus Effizienzgründen. Die vollständige Liste besonderer Matrixformate ist in der [Dokumentation](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Special-matrices) zu finden.

Hier beschränken wir uns auf Diagonalmatrizen `Diagonal`:

In [21]:
Diagonal([1,2,3])

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

### Matrixinversion

Das Inverse einer Matrix kann mit der Funktion `inv()` berechnet werden:

In [22]:
M = rand(3,3)
M_inv = inv(M)

3×3 Matrix{Float64}:
 11.312    -8.69129   5.33094
 -7.91229   7.38889  -5.82996
 -3.58767   2.55757   0.825631

In [23]:
M_inv*M

3×3 Matrix{Float64}:
 1.0          7.21645e-16  -4.44089e-16
 0.0          1.0           4.44089e-16
 3.05311e-16  1.38778e-17   1.0

Ein typisches Problem, das durch Matrixinversion gelöst werden kann, ist das Lösen eines linearen Gleichungssystems, z.B.

$$\begin{pmatrix}1&2&3\\-3&2&5\\0&6&23\end{pmatrix}\begin{pmatrix}x_1\\x_2\\x_3\end{pmatrix}=\begin{pmatrix}42\\13\\1\end{pmatrix}$$

Wir legen also entsprechend eine Matrix und einen Vektor an:

In [25]:
A = [1.0 -3.0 0.0; 2.0 2.0 6.0; 3.0 5.0 23.0]
b = [42.0, 13.0, 1.0]

3-element Vector{Float64}:
 42.0
 13.0
  1.0

Und wir erhalten die Lösung als $\vec x=A^{-1}\vec b$

In [26]:
x = inv(A) * b

3-element Vector{Float64}:
 15.51
 -8.829999999999998
 -0.060000000000000456

"Probe Rechnen":

In [ ]:
A*x-b

3-element Vector{Float64}:
 -7.105427357601002e-15
  0.0
 -7.771561172376096e-16

Übersichtlicheres "Probe Rechnen" mit `isapprox()`:

In [29]:
isapprox(A*x,b)

true

Alternativ kannn das Gleichungssystem durch den Linksdivisionsoperator `\` gelöst werden. Da wir uns am Ende nur für das Produkt $A^{-1}\vec b$ interessieren, kann es Julia in diesem Fall vermeiden, die Matrix explizit zu invertieren, und stattdessen einen effizienteren Algorithmus verwenden:

In [32]:
x1=A\b

3-element Vector{Float64}:
 15.509999999999998
 -8.829999999999997
 -0.0600000000000006

In [33]:
isapprox(x,x1)

true

### Besondere Funktionen von Matrizen und Vektoren

Die üblichen Funktionen, die wir auf Matrizen und Vektoren ausrechnen wollen, sind implementiert:

Norm `norm()` (standardmäßig $L^2$ Norm):

In [34]:
norm(x)

17.847481615062666

In [35]:
norm(A)

24.839484696748443

$L^p$ Norm durch ein weiteres Argument:

In [36]:
norm(x,7)

15.55259672644727

Determinante `det()`:

In [37]:
det(A)

100.0

Spur `tr()`:

In [38]:
tr(A)

26.0

Rang `rank()`:

In [40]:
rank(A)

3

### Eigenwertprobleme

Durch Eigenzerlegung einer Matrix $M$ finden wir Eigenwerte $\vec\lambda$ und eine Matrix $V$, deren Spalten den Eigenvektoren entsprechen, so dass

$$M = V \cdot \text{diag}\big(\vec\lambda\big) \cdot V^{-1}$$

Auch das ist in Julia ein Einzeiler:

In [48]:
lambda, V = eigen(A)

Eigen{ComplexF64, ComplexF64, Matrix{ComplexF64}, Vector{ComplexF64}}
values:
3-element Vector{ComplexF64}:
 0.8846859357719979 - 1.8287533881621232im
 0.8846859357719979 + 1.8287533881621232im
  24.23062812845602 + 0.0im
vectors:
3×3 Matrix{ComplexF64}:
  -0.841368-0.0im        -0.841368+0.0im       0.0332714+0.0im
 -0.0323405-0.512885im  -0.0323405+0.512885im  -0.257639+0.0im
   0.130144+0.105195im    0.130144-0.105195im  -0.965668+0.0im

In [49]:
isapprox(A, V * Diagonal(lambda) * inv(V))

true

Es können auch jeweils nur Eigenwerte oder nur Eigenvektoren berechnet werden:

In [ ]:
lambda = eigvals(A)

3×3 Matrix{ComplexF64}:
  -0.841368-0.0im        -0.841368+0.0im       0.0332714+0.0im
 -0.0323405-0.512885im  -0.0323405+0.512885im  -0.257639+0.0im
   0.130144+0.105195im    0.130144-0.105195im  -0.965668+0.0im

In [50]:
lambda = eigvecs(A)

3×3 Matrix{ComplexF64}:
  -0.841368-0.0im        -0.841368+0.0im       0.0332714+0.0im
 -0.0323405-0.512885im  -0.0323405+0.512885im  -0.257639+0.0im
   0.130144+0.105195im    0.130144-0.105195im  -0.965668+0.0im

### Singulärwertzerlegung

Durch Eigenzerlegung einer Matrix $M$ finden wir Singulärwerte $\vec\sigma$ und zwei unitäre Matrizen $U$ und $V$, so dass

$$M = U \cdot \text{diag}\big(\vec\sigma\big) \cdot V^{\dagger}$$

Auch das ist in Julia ein Einzeiler:

In [51]:
U, sigma, V = svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
  0.0212047   0.996202   -0.0844512
 -0.264569   -0.0758676  -0.961378
 -0.964134    0.0427289   0.261955
singular values:
3-element Vector{Float64}:
 24.60738043552128
  3.128885785804746
  1.2988078537310093
Vt factor:
3×3 Matrix{Float64}:
 -0.138183  -0.219992  -0.965665
  0.310863  -0.93538    0.168609
 -0.940356  -0.27689    0.197641

In [52]:
U' * U

3×3 Matrix{Float64}:
  1.0           2.42861e-16  -1.11022e-16
  2.42861e-16   1.0          -9.54098e-17
 -1.11022e-16  -9.54098e-17   1.0

In [53]:
isapprox(A, U * Diagonal(sigma) * V')

true

### QR-Zerlegung

Durch Eigenzerlegung einer Matrix $M$ finden wir eine unitäre Matrix $Q$ und eine obere Dreiecksmatrix $R$, so dass

$$M = Q\cdot R$$

Auch das ist in Julia ein Einzeiler:

In [54]:
Q, R = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -3.74166  -4.27618  -21.6482
  0.0      -4.44008   -7.75405
  0.0       0.0        6.01929

In [55]:
isapprox(A, Q*R)

true

In [56]:
Q' * Q

3×3 Matrix{Float64}:
 1.0           2.22045e-16   1.38778e-16
 1.11022e-16   1.0          -1.11022e-16
 0.0          -1.11022e-16   1.0

In [ ]:
R

3×3 Matrix{Float64}:
 -3.74166  -4.27618  -21.6482
  0.0      -4.44008   -7.75405
  0.0       0.0        6.01929