<table style="width: 100%; border-style: none;">
<tr style="border-style: none">
<td style="border-style: none; width: 1%; text-align: left; font-size: 16px">Institut f&uuml;r Theoretische Physik<br /> Universit&auml;t zu K&ouml;ln</td>
<td style="border-style: none; width: 1%; font-size: 16px">&nbsp;</td>
<td style="border-style: none; width: 1%; text-align: right; font-size: 16px">Prof. Dr. Matteo Rizzi
<br />Erik Weerda</td>
</tr>
</table>
<hr>
<h1 style="font-weight:bold; text-align: center; margin: 0px; font-size: 30px; padding:0px;">Computerphysik</h1>
<h1 style="font-weight:bold; text-align: center; margin: 0px; font-size: 30px; padding:0px;">Übungsblatt 3</h1>
<hr>
<h3 style="font-weight:bold; text-align: center; margin: 0px; font-size: 20px; padding:0px; margin-bottom: 20px;">Sommersemester 2026</h3>
<hr>



<table style="border-style: none; width: 100%"><tr style="border-style: none;">
<td style="border-style: none; width: 1%; text-align: left; font-size: 25px; font-weight: bold; text-decoration: underline">Aufgaben auf Übungsblatt 3</td>
<td style="border-style: none; width: 1%; text-align: right; font-size: 15px"></td></tr></table>

- **LR-Zerlegung (d.h., LU-Zerlegung)** [2 Punkte]
- Geschwindigkeitsmessung [1 Punkt]

<table style="border-style: none; width: 100%"><tr style="border-style: none;">
<td style="border-style: none; width: 1%; text-align: left; font-size: 25px; font-weight: bold; text-decoration: underline">LR-Zerlegung (d.h., LU-Zerlegung) </td>


In dieser Aufgabe soll für die Lösung von linearen Gleichungssystemen die sogenannte **LR**-Zerlegung implementiert werden, die Sie in der Vorlesung als **LU**-Zerlegung kennengelernt haben (**L**inks-**R**echts, oder **L**ower-**U**pper).
Die LR-Zerlegung ist im Prinzip das Gaußsche Eliminationsverfahren, das Sie wahrscheinlich schon aus der Schule kennen, nur dass die Umformungsschritte in der Matrix $L$ gespeichert werden. Das Ergebnis einer LR-Zerlegung einer Matrix $A$ ist eine untere Dreiecksmatrix mit einsen auf der Diagonalen $L$ und eine obere Dreiecksmatrix $R$ für die gilt $A = L \cdot R$ (bzw. $A = L \cdot U$ in der Notation der Vorlesung).

Solch eine Zerlegung ist sinnvoll für die Lösung von Gleichungssystemen. Betrachten wir dazu ein Gleichungsystem $Ax=b$ mit LR-Zerlegung $A = LR$. Dies kann man schreiben als

$$ L \underbrace{Rx}_{y} = b .$$

Somit kann eine Lösung des Gleichungssystems durch die folgenden zwei Schritte erfolgen:

1. Bestimme die Lösung $y$ der Gleichungssystems $Ly = b$ mit $y = Rx$ durch Vorwärtseinsetzen

2. Bestimme die Lösung $x$ des Gleichungssystems $Rx=y$ durch Rückwertseinsetzen.


Da $L$ und $R$ jeweils untere bzw. obere Dreiecksmatrizen sind, können die Gleichungssysteme sehr effizient für beliebige $b$ durch Vorwärts- bzw. Rückwertseinsetzen gelöst werden. 

Das Vorgehen bei einer LR-Zerlegung haben Sie im Detail in dem Vorlesungsvideo 4-c mithilfe eines konkreten Beispiels gesehen: Falls noch nicht gemacht, schauen Sie es bitte da nochmal an.

Wir starten dafür mit der Matrix $R_0 = A$ und anschließend gehen wir iterativ vor.
Im $i$-ten Schritt müssen nun die Zahlen der $i$-ten Spalte unter der Diagonale auf 0 gesetzt werden. Dies geschieht durch die Addition von Vielfachen der $i-$ten Zeile auf die unteren Zeilen. 
Genau diese Operation kann als Multiplikation mit einer linken unteren Dreiecksmatrix $(L_i)^{-1}$ geschrieben werden:
$$
L_i^{-1} = \begin{pmatrix}
1 & & & & & \\
& \ddots & & & & \\
& & 1 & & & \\
& & -l_{i+1, i} & 1 & & \\
& & \vdots & & \ddots & \\
& & -l_{N, i} & & & 1
\end{pmatrix} 
\Longleftrightarrow
L_i = \begin{pmatrix}
1 & & & & & \\
& \ddots & & & & \\
& & 1 & & & \\
& & l_{i+1, i} & 1 & & \\
& & \vdots & & \ddots & \\
& & l_{N, i} & & & 1
\end{pmatrix}
$$
Die Elemente $l_{ji}$ der Matrix $L_i$ sind dabei im i-ten Schritt gegeben durch 
$$l_{ji} = \frac{(R_{i-1})_{ji}}{(R_{i-1})_{ii}} \quad \forall j>i.$$

Damit lässt sich die ursprüngliche Matrix als 
$$A = R_0 = L_1 R_1 = L_1 (L_2 R_2) = \left(\prod_{i=1}^{N-1} L_i\right) R_{N-1} \equiv L R$$
umschreiben. 
Besonders einfach ist dies, da das Produkt für untere Dreiecksmatrizen einfach der Summe entspricht, ausgenommen der Diagonale:
$$
\prod_{i=1}^{N-1} L_i = 
\begin{pmatrix}
1 & & & & & \\
l_{2, 1}& \ddots & & & & \\
&\ddots & 1 & & & \\
\vdots & & l_{i+1, i} & 1 & & \\
& & \vdots & \ddots & \ddots & \\
l_{N, 1}& \ldots & l_{N, i} & \ldots & l_{N, N-1} & 1
\end{pmatrix}
$$




### a) LR-Zerlegung mit Stift und Papier

Führen Sie die LR-Zerlegung der unten definierten Matrix `A` per Hand durch. Sie können für die Abgabe ihre Rechnung scannen und als PDF-Datei mit hochladen.

In [2]:
A = Float64[2 -4 -4 -6
            3 -9  0 -9
           -1  2  4  7
           -3 -6 26  2]
display(A)

4×4 Matrix{Float64}:
  2.0  -4.0  -4.0  -6.0
  3.0  -9.0   0.0  -9.0
 -1.0   2.0   4.0   7.0
 -3.0  -6.0  26.0   2.0

### b) Implementierung der LR-Zerlegung

Ergänzen sie die Funktion `LR_Zerlegung`, sodass sie die LR-Zerlegung einer beliebigen quadratischen Matrix `A` berechnet. 

*Anmerkung*: Sie sollen davon ausgehen, dass keine Zeilenvertauschungen im Algorithmus nötig sind.  
*Anmerkung*: Sollten sie hier keine funktionierende Lösung finden, können sie alle nachfolgenden Aufgaben auch mit der Julia-Funktion  
`lu(A, val{false})` lösen.  Das Argument `val{false}` ist dafür da, dass keine Zeilen während der LR-Zerlegung vertauscht werden. Das ist normalerweise nicht sinnvoll, doch hier für den Vergleich schon.

In [ ]:
using LinearAlgebra 

function LR_Zerlegung(A)
    
    #Anzahl an Zeilen/Spalten
    N = size(A, 1)
    
    #L Matrix als Einheitsmatrix initialisiert
    L = Matrix{Float64}(I, N, N)
    
    #R Matrix wird initialisiert als A
    R = copy(A)

    #Schleife über die Zeilen von A (Letzte Zeile nicht nötig)

    #j-te Spalte
        for j in 1:N-1

    #L Wert der i-te Zeile
            for i in j+1:N
                L[i,j]=R[i,j]/R[j,j]

    #Zeilen addieren
                for k in 1:N
                    R[i,k]=R[i,k]-L[i,j]*R[j,k]
                end
            end
        end
    return L, R
end

4×4 Matrix{Float64}:
  1.0   0.0   0.0  0.0
  1.5   1.0   0.0  0.0
 -0.5  -0.0   1.0  0.0
 -1.5   4.0  -2.0  1.0

4×4 Matrix{Float64}:
 2.0  -4.0  -4.0  -6.0
 0.0  -3.0   6.0   0.0
 0.0   0.0   2.0   4.0
 0.0   0.0   0.0   1.0

Testen sie nun ihre Funktion durch die nachfolgenden Zellen.

In [5]:
L, R = LR_Zerlegung(A)
display(L)
display(R)
display(L*R ≈ A)

4×4 Matrix{Float64}:
  1.0   0.0   0.0  0.0
  1.5   1.0   0.0  0.0
 -0.5  -0.0   1.0  0.0
 -1.5   4.0  -2.0  1.0

4×4 Matrix{Float64}:
 2.0  -4.0  -4.0  -6.0
 0.0  -3.0   6.0   0.0
 0.0   0.0   2.0   4.0
 0.0   0.0   0.0   1.0

true

Zur Kontrolle können Sie auch mit Julias interner Funktion vergleichen

In [6]:
l, r = lu(A, Val(false))
display(l)
display(r)
display(l*r ≈ A)

4×4 Matrix{Float64}:
  1.0   0.0   0.0  0.0
  1.5   1.0   0.0  0.0
 -0.5  -0.0   1.0  0.0
 -1.5   4.0  -2.0  1.0

4×4 Matrix{Float64}:
 2.0  -4.0  -4.0  -6.0
 0.0  -3.0   6.0   0.0
 0.0   0.0   2.0   4.0
 0.0   0.0   0.0   1.0

true

### c) Vorwärts und Rückwerts einsetzen

Um nun ein Gleichungssystem der Form $Ax = b$ mittels LR-Zerlegung zu lösen, muss, wie oben schon beschrieben, noch das Vorwärts bzw. Rückwertseinsetzen implementiert werden. 

Mit Vorwärtseinsetzen ist gemeint, die Lösung $y$ eines Gleichungssystem der Form

$
\begin{pmatrix}
l_{11} & 0 & 0  & \ddots & 0 \\
l_{21} & l_{22} & 0 & & \vdots \\
l_{31} & l_{32} & l_{33} & \ddots & \vdots \\
\vdots & \vdots & \vdots & \ddots & 0 \\
l_{N1} & l_{N2} & l_{N3} & \ddots & l_{NN}
\end{pmatrix}
\cdot
\begin{pmatrix} y_1 \\ y_2 \\ y_3 \\ \vdots \\y_n \end{pmatrix} =
\begin{pmatrix} b_1 \\ b_2 \\ b_3 \\ \vdots \\b_n \end{pmatrix}
$

zu berechnen, in dem man zunächst aus der ersten Zeile 

$y_1 = \frac{b_1}{l_{11}}$ 

bestimmt, das Ergebnis in die Zweite Zeile einsetzt und 

$y_2 = \frac{b_2 - y_1 l_{21}}{l_{22}}$ 

bestimmt, usw ..

Die Formel für ein allgemeines $i$ lautet:

$ y_i = \frac{1}{l_{ii}}\left(b_i - \sum_{k=1}^{i-1} l_{ik} y_k \right). $

Rückwerts einsetzen ist dasselbe Prinzip, nur das die Lösung $x$ des Gleichungssystems $Rx = y$ mit oberer rechter Dreiecksmatrix $R$  berechnet wird, und somit mit der letzten statt der ersten Zeile angefangen werden muss. Die spezielle Formel für ein $x_i$ ändert sich dementsprechend auch ein wenig. 

Vervollständigen Sie die unteren Funktionen um beide Verfahren zu implementieren.

In [ ]:
function vorwaertseinsetzen(L, b)
    
    #Anzahl an Zeilen/Spalten
    N = size(L, 1)
    
    #Lösungsvektor definieren
    y = zeros(N)
    
    #Schleife über die Zeilen
    for i in 1:N
        
        ## Hier sollte Ihr Code stehen ##
    
    end
    
    #Lösungsvektor wiedergeben
    return y
end

In [ ]:
function rueckwertseinsetzen(R, y)
    
    #Anzahl an Zeilen/Spalten
    N = size(R, 1)
    
    #Lösungsvektor definieren
    x = zeros(N)
    
    #Schleife über die Zeilen (von unten nach oben)
    for i in N:-1:1
        
       ## Hier sollte ihr Code stehen ##
    
    end
    
    #Lösungsvektor wiedergeben
    return x
    
end

Testen sie ihre Lösung, indem sie die Lösung $x$ des Gleichungssystems $Ax = b$ mit den unten definierten `A` und `b` bestimmen. Bestimmen Sie dazu zunächst eine LR-Zerlegung von `A`. Lösen Sie anschließend das Gleichungssystem $Ly = b$ mit $y=Rx$ durch Vorwärtseinsetzen und dann das Gleichungssytem $Rx = y$ durch Rückwertseinsetzen. Vergleichen sie anschließend mit der Lösung durch Julia-Funktionen, welche in der unteren Zele schon implementiert ist.

*Hinweis*: Wie oben schon erwähnt, können sie bei fehlender Aufgabe b) für die LR-Zerlegung auch die Julia Funktion `lu(A, Val(false))` verwenden.

In [ ]:
A = Float64[3  4 -5  6
     6  5 -6  5
     9 -4  2  3
     0  2 -3  1]

b = [39, 43, 6, 13]

## Lösung mit Juliafunktionen zum Vergleich
l, r = lu(A, Val(false)) #LR Zerlegung

#Vorwärtseinsetzen
y_julia = l \ b 
println("y = $y_julia")

# Rückwertseinsetzen
x_julia = r \ y_julia
println("x = $x_julia") 

#Direkte Julialösung
x_julia_direkt = A \ b
println("x_direkt = $x_julia_direkt")

In [ ]:
## Hier sollte ihr Code mit ihren eigenen Funktionen stehen ##

### d)  Benchmarken mit Random-Matrizen

Schreiben sie nun eine Funktion, die die LR-Zerlegung und Vor- und Rückwertseinsetzen kombiniert, und direkt die Lösung eines allgemeinen Gleichungssystems ausgibt. Sie können ihre Lösung anhand der Julia-Lösung der Aufgabe c) kontrollieren.

In [ ]:
function loese_lgs(A, b)
    
    ## Hier ihren Code ergänzen ##
    
    #Lösungsvektor zurückgeben
    return x
end

In [ ]:
#Test mit Julia-Loesung:
x = loese_lgs(A, b)
x ≈ A\b

Nun wollen wir die Geschwindigkeit der selbstgeschriebenen Funktion mit der Julia-Funktion `x = A\b` vergleichen und das ganze in Abhängigkeit der Größe der Matrix. Führen sie dazu die nachfolgende Zelle einfach aus. Es wird hier für verschiedene Matrixgrößen die Zeit gemessen, die für die Lösung eines zufällig generierten Gleichungssystems benötigt wird. Was fällt ihnen auf?

*Anmerkung*: Das ausführen kann einige Zeit dauern. Wenn es bei ihnen zu lange dauert, reduzieren sie die Werte in `N_werte`.

In [ ]:
using BenchmarkTools

#Matrixgrößen definieren
N_werte = [10, 100, 1000]

for N in N_werte
    
    #Zufällige Matrix und Vektor definieren
    A = rand(N, N)
    b = rand(N)
    
    #Lösung des Gleichungssystems timen und printen
    println("N = ", N)
    
    println("Julia-Lösung: ")
    @btime $A\$b 
    
    println("Eigene Lösung: ")
    @btime loese_lgs($A, $b)
    
    println()
    
end